---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
data <- read.csv(unz("activity.zip", "activity.csv"), header = TRUE)
data[,2] <- as.Date(data[,2])
```

## What is mean total number of steps taken per day?
```{r}
totals <- tapply(data$steps, data$date, sum, na.rm = TRUE)
hist(totals)
means <- tapply(data$steps, data$date, mean, na.rm = TRUE)
means[is.nan(means)] <- 0
medians <- tapply(data$steps, data$date, median, na.rm = TRUE)
medians[is.nan(medians)] <- 0
aves <- rbind(means, medians)
print(aves)
```

## What is the average daily activity pattern?

```{r}
adaPattern <- tapply(data$steps, data$interval, mean, na.rm = TRUE)
plot(adaPattern, type = 'l')
guys <- which.max(adaPattern)
names(guys)
```


## Imputing missing values
```{r}
nas <- (is.na(data[,1]) | is.na(data[,2]) | is.na(data[,3]))
length(nas[nas])
data[nas, 1] <- adaPattern[nas] 
totals <- tapply(data$steps, data$date, sum, na.rm = TRUE)
hist(totals)
means <- tapply(data$steps, data$date, mean, na.rm = TRUE)
means
medians <- tapply(data$steps, data$date, median, na.rm = TRUE)
medians
```
## Are there differences in activity patterns between weekdays and weekends?

```{r}
data['Weekday'] <- TRUE
data[(weekdays.Date(data$date) == "Saturday"), 'Weekday'] <- FALSE
data[(weekdays.Date(data$date) == "Sunday"), 'Weekday'] <- FALSE
weekdayData <- data[data$Weekday,]
weekendData <- data[!data$Weekday,]
weekdayPattern <- tapply(weekdayData$steps, 
weekdayData$interval, mean, na.rm = TRUE)
par(mfrow = c(2,1))
plot(weekdayPattern, type = 'l')
weekendPattern <- tapply(weekendData$steps, 
weekendData$interval, mean, na.rm = TRUE)
plot(weekendPattern, type = 'l')
```